name: IAM Terraform Plan

on:
  pull_request:
    paths:
      - "onprem-web-migration/iam/**"
      - ".github/workflows/iam-terraform-plan.yml"

  push:
    branches:
      - main
    paths:
      - "onprem-web-migration/iam/**"
      - ".github/workflows/iam-terraform-plan.yml"

permissions:
  contents: read
  id-token: write

env:
  PROJECT_ID: employee-dev-505820
  TF_WORKING_DIR: onprem-web-migration/iam

jobs:
  terraform-plan:
    name: IAM Terraform Plan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v3
        with:
          workload_identity_provider: projects/393053843777/locations/global/workloadIdentityPools/github-actions/providers/github
          service_account: terraform-deployer@employee-dev-505820.iam.gserviceaccount.com

      - name: Set up Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Format Check
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform fmt -check

      - name: Terraform Init
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform init

      - name: Terraform Validate
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform validate

      - name: Terraform Plan
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform plan -out=tfplan

      - name: Export Terraform Plan
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform show -no-color tfplan > tfplan.txt

      - name: Upload Terraform Plan
        uses: actions/upload-artifact@v4
        with:
          name: iam-terraform-plan
          path: |
            onprem-web-migration/iam/tfplan
            onprem-web-migration/iam/tfplan.txt